version: "3"

services:
  frontend:
    environment:
      CHOKIDAR_USEPOLLING: "true" 
    build: 
      context: .
      dockerfile: .
    container_name: hello_world_react
    volumes:
      - ./hello-world/src:/app/src
    restart: always
    ports:
      - 3000:3000